#!/usr/bin/python3
#---Read the code---
with open('HappyBirthday.py') as f_in:
	code = f_in.read()

face =\
'''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                   .                    ..      .                                                                                                                                                                                                                                                                                                                 
                                                                                                                 ...........  .....      ...     ......                                                                                                                                                                                                                                                                                                           
                                                                                                               ..        .......                         ..                                                                                                                                                                                                                                                                                                       
                                                                                                              .             ...                                ....                                                                                                                                                                                                                                                                                               
                                                                                                        ......  ...        ...                                          ..                                                                                                                                                                                                                                                                                        
                                                                                                     ....     ....   .     .     .                                      ....                                                                                                                                                                                                                                                                                      
                                                                                                    ........                   ..                                            .....                                                                                                                                                                                                                                                                                
                                                                                                    ...                                 ..                                        .                                                                                                                                                                                                                                                                               
                                                                                                   ..                                  ..             .                                                                                                                                                                                                                                                                                                           
                                                                                                   .                                  ..      ..     ..       ..                   . .....                                                                                                                                                                                                                                                                        
                                                                                                 .                                          ...       .        .                         ..                                                                                                                                                                                                                                                                       
                                                                                                             ....,....                                   .    .                          ..                                                                                                                                                                                                                                                                       
                                                                                      ...                     ...,,,,,,,...                                  .                            ..                                                                                                                                                                                                                                                                      
                                                                                    ...                        .    ..,,,,,,..                                                               .                                                                                                                                                                                                                                                                    
                                                                                   ..                                .......,......                                       .                  .                                                                                                                                                                                                                                                                    
                                                                                  ..               .                        .....,,,...                                   .                  .                                                                                                                                                                                                                                                                    
                                                                                 .               ..                             ..,,;;,,......                                                .                                                                                                                                                                                                                                                                   
                                                                                ..                                               ...,;::,,,,,,,........                                         .                                                                                                                                                                                                                                                                 
                                                                               ..                          .      .               ...,:cccclcc::;;;,,,,.....                                    .                                                                                                                                                                                                                                                                 
                                                                              ..                                ...  ..            ..,:cooodxdooolcc:;;;;,,....                                ..                                                                                                                                                                                                                                                                 
                                                                              .                                 ..  .,.            ..,codddxxxxxxxddoolccc:;;,,...                            ..                                                                                                                                                                                                                                                                  
                                                                             ..                           ...     ..... ......    ...,ldxxdxxxxxxxxxxxdooooollc:;,,....                      ..                                                                                                                                                                                                                                                                   
                                                                             .                         .........          .. .......,:lxkxxxxxxxxxxxxxxxddddddoollc::;,...                 ..                                                                                                                                                                                                                                                                     
                                                                            ..                     .....................     ......,,cdxxxxxkxxxxxxxxxxxxxxxxddoooolllc:;,..           ...                                                                                                                                                                                                                                                                        
                                                                            ..               .........................,...........,;:lxxxxxkkkxxxxxxxxxxxxxxxdddddoooolllc:,..       ...                                                                                                                                                                                                                                                                          
                                                                            .              ...........,,,,..,,,,,,,,,,,,,,......,,;;ldxxxkkkkkkkxxxxxxxxxxxxxddddddoooollllc:;,....                                                                                                                                                                                                                                                                               
                                                                            .             .....,.,,,,;;,,,,;:;;;;,;:;,,::;;,,,,,;::ldxxxxxxkkkkkkxxxxxxxxxxxddddddddooooolllllc:;,,.                                                                                                                                                                                                                                                                              
                                                                            .           .....,,,,,,;;;;::::::ccc::ccc:cccllccccccllooddxxxxkkkkkkxxxxxxxxxxddddddddddooooolllllcc::,.                                                                                                                                                                                                                                                                             
                                                                            .         ....,,,,;;;;:::::::cccclccllllllooodoollollllloddxxxxkkkkkxxxxxxxxxxdddddddddddooooooollllccc:,                                                                                                                                                                                                                                                                             
                                                                           ..        ....,,,;;:::::::::::::cclllllllloooooooooooooodddxxxxxxkkkxxxxxxxxddddddddddddoddooooooollllccc:.                                                                                                                                                                                                                                                                            
                                                                           ..       ...,,;;:::cc::ccc:cc::cclllclllllllllloooooooodddxxxxxxkxxxxxxxxxxdddddddddodddddoooooooollllcccc,                                                                                                                                                                                                                                                                            
                                                                           ..       ..,,;;::cccc:cccccccllclcccllllllooddddooooddxxxxkkkkkkkxxxxxxxxxxxddddddddddddoooooooollllllcccc;.                                                                                                                                                                                                                                                                           
                                                                           ..      ..,,;,;:cccc:::::;;:clcccccclclooddxxkkxxxxxxxxkkkkkkkkkkxxxxxxkxxxxxdddddddddoddooooooollllllcccc:.                                                                                                                                                                                                                                                                           
                                                                           ..    .,;:ccc:::::::c:::::::cc:cclcllllodxkkkkkkkkOOOkkkOOOOOkkkxxxxxxxkkxxxxdddddddddddddoooooolllllllccc;.                                                                                                                                                                                                                                                                           
                                                                           ..  .,codoooddol:::::;;;cccc:::clcccllodxxkkkkkkkkkOOkOOOOOkkkkkkkxxxxxxxxxxxxdddddddddddddooooollollllcc:;.                                                                                                                                                                                                                                                                           
                                                                            . .cdoc;:ccloddolcc:;;:::::::ccccccllodxkkkkkkkkkkkOOOOOOkkkkxdoolllooodddddddddddooodddddoooooooooollcc:,                                                                                                                                                                                                                                                                            
                                                                           ...ld:,:ldkkOkxxxdlcllc:ccc::c:::ccccodxkkOOOOOOkkkOOOOOOkxdlc;;,,,,,,,,,,,,,;:clooooooddddoooooooooolllc:.                                                                                                                                                                                                                                                                            
                                                                           ..ld:,cdkkO00Oxdoddoooolccccccccc:cloddxkkOOOOOOOkkOkkxdolcc:::::;;,,...... ....,:clloooodddoooooooooollc;.                                                                                                                                                                                                                                                                            
                                                                           .;xo;:dxxk00Okdoddddddxxdlccc:cccccoddxkkOOOOOOOOOkkkxdoolloodddoollcc:::;,...  ...,;:clloddoooooooooooll,                                                                                                                                                                                                                                                                             
                                                                           .cxl;okxkO0Okkxdkkxxxxxkkxocc:;clccoodxkkOOOOOOOOOOkkkxxddddddddooooooollllc:,,.   ...,:clooooloooooooolc,                                                                                                                                                                                                                                                                             
                                                                           .cxlcdxxO0Okkxxdoddxxxxkkkxolc:clcclodkkkOOOOOOOOOOkkkkxxxddddoooollllllccccc::,...   ...,:ccccloloooolc:,.                                                                                                                                                                                                                                                                            
                                                                          ..;doldxkOkxdol:;:lodddxxxxxdlc:clloodxkkOOOOOOOOOOOOkkkkxxddoolc:;:::c:;,,,,,,,,,,...    ...,;:cclloool:;,.                                                                                                                                                                                                                                                                            
                                                                          ..,ldloxkkdllc::lkkdoodxxxxxdc;;:cldxxkkkkkkOOOOOOOOOOkkkxxddolc:;,,,.,,....,,,.........    ...,;clloolc;,...                                                                                                                                                                                                                                                                           
                                                                          ...:doldkkoc::cdkkdolldxxxxxdl:;;codxxxkkkkkkOOOOOOOkkkkxxxdoolc:;,;,......,olc,.....,,....  ..,;::::::,..                                                                                            .                                                                                                                                                                                 
                                                                          ...,odloxkdccldOOkxoldkkkkkxdoc;;cooddxxkkkkkOOOOOOOOkkkxxxxxddooooolc;,.,;oxxoc,....,,;:;,...,;;,......  .                                                                                          ...                                                                                  ..                             ,lc.  .;c;,.        .ll;,.                                     
                                                                          ...,cxdodkkdlldxkxxxxkOkkkkxxoc;;:clodxxkkkkkkkOOOOOkkkkkkxxxxxddddooolccclool:;,...,;:ldxxdolcc,.                                                                            .....,,,,.            .;;,;,   ,l,                                                   ..         ......   .:;,. .;c,                      ,dko;. ,xd..,        ,0O, ;,                                     
                                                                          ...,;oxddxxkdooddxOOkxdxkkkkdl:;;::coddxkkkkkkkkkOOOkkkkkkxxxxxxxdddoollcc:::;;,,.,,:lodxkOOkxdo, .,,.                                                                   .............;ll.         ,ko..lc .l0c                                                 .,:,       .;,,....,:..kk...,k0:..:o,                 ;Od,,. ;0d...        ,OK; .:,                                     
                                                                          ...,;ldxdxxxkkkkkxkkxdldkkkxdc;,,;::lodxxxxxkkkkkkOOOOOkkkxxxxxxxxxxddollc::;;,,,,,coodxkkOOOkxdc,,:;.                                                                .....             ox.   ....,0K:...;dkXl                                                 ,o:.      ,ll,      .xc.:c,..dXd...;0K,   .c,         c0x,.  :Kx...        .dNl .,.                                      
                                                                          ..,,:codxxxkkkkkOkxdddodkkkxo:;;;;;:clddxxxxxxkkkkkOOOOOOkkxxxxxxxxxxxxddoollccc::lodxxkkOOOOOkxd:,,..                                                             .,..           ......:kc...,..,OXl.   .dNx.                                               .lk;      ,dx,        c0;   .oON0, . .xWo.. .c,        :X0:.  ;K0:..         :Xk..,.                                       
                                                                          ..,;clloxkkkkkkkkkkkkxxxkkkxl;,,:;;::loddxxxxxkkkkkkkOOOOkkkkxxxxxxxxxxxxxddddddddxxxkkOOOOOOOOkxd:,.                                                            .,..      .....   .    .;.   .. ;xo;,...,dO,    .                                           cK:      ;0d.       .ok;    ,0MMWo...:NWxc,..         ,0K:.  .ONd,.      .  .kK:..  .                                      
                                                                         ...,:cllooxkkkxkkkkkkkkkxxxxxl;,,;:;;:coddxxxxxxkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxkkkOOOOOOOOOOOkxd;                                                           ...      .....           :c     ,d0k,.,,..cxc. .:;,;ol. ,c;.cx, .;c;.ld. ,do..:d:            .od.     .xo.   ,:. .lo.  ...,lxl:.   ,dl, .dd,.,co:ol.oXdc:;.lN0dko.   ;ol,.lKd...:;,;ol..ox, ,dc                          
                                                                         ..,,:coooooxkkkOOkkkkkkxddxxdc,,,;:::;:oddxxxxxxxkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxkkOOOOOOOOOOOOOOkkl.                                                         ..      ,:,              ;d.     .xXc     ;KO..ck:..dx,.oKd. cNd.dKl..oNl ;Kx.:Xx.             ox.     ;O,   ,xxllo,.....  ,xc       ,d,.x0, ,O0:,odo0x.   ,0k,.kO.  :kc  ,dc..cO:..dx, ,00,,0O,                          
                                                                         .,,;:coooooddkkOkkkkkkdlldxdl:,,.,:::::lodxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkOOOOOOOOOOOOOkkxc.                                                       ..      :o.         ...  :o,      lXd. ,, ,00, ;0l .dK; cX0, ;XNxxNO, cNNo:00,.kKc..            ,kc     .lc. .;llc;.  .    .kx.     .. codKl  lXl   .:Xl   ;0O, .xk. cKo  .do..c0l .dK; .kK;.dXo..                         
                                                                        .,;,;:cloooddoodxxxxxdl;,lddoc;,,,,:::ccccoxxkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkOOOOOOkkOOOOkkxx;                                                      .       ,Oc            .,c:.     .lKo.  .,;kk,  .xc.,kKlcKXl,:odcoXK:,:dd:.,xd,oNk,               .;,......,;,,;;,.        ,xd,.     ..,KN0o. :xc.    .kOc,c0k,   ;kl,,xo..c0k;.,xl.,kKl,,dx;cXO;                           
                                                                       .,:::;:clloodddollccc:,..;odoc:;,,,,,;::cccodxkkkkkxxxxxxxxddddddddddxxxxxxxxxxdddddxkkkkkkkkkkkOOOOOkxxo,                                                             .kl           .,,.      .;l,     ,l;     .......dNd.  . .xNl        .;oXO.                   ........             .:;.  .....;o0O:.   .        .,...,      ..  ...  ..   .......  .,lKK;                            
                                                                       .;ccccccclloddddolc:;,.,;llll:,,,,,,,,;;;:clodxxxxxxxxxxxxxddddddddddddxxxxxxxdddodxkxkkkkkkkkOOOOOOOkkxd:.                                                             ,oc..  .......                                :Kk.     lXx.       .oXWK;                                                 .;ccc,.                                                 cKWNc                             
                                                                      .;cccccccllllodxxdolodolcllc::,,,,,,,,,,;;::cldxxxxxxddddddddddddddddddddxxddddddodxxxxkOOOOOOkkkxxkkxxxdd;                                                                .,,......                                 ,oOd.   .,dOl.       .dWMK:                                                                                                         lNMNl                              
                                                                      ,cccccccclllllodxxdoldxxol:;,;,,.,..,,,,,;;::coooddxddddddddddddddddddddddddddddddddddxxxdl:;,,,;;:codool;.                                                                                                         .,,.     .,,.          :kd,                                                                                                          ,xx;                               
                                                                     .;ccccllcccloollodxxdlldkdl:,,,,,,....,,,;;;::;lcclooooooooooodddddddddddddddddodddddoolc:;,,,;::;;;;cl:,.                                                                                                                                                                                                                                                                                   
                                                                     ,clcllllllcclodolodxxdlldxo:,,........,,,;,;::;::::cccloooooooodddxxxxddxddddooddxxxxxdlccloooool:;;,..                                                                                                                                                                                                                                                                                      
                                                                    .;lllllllllllcldddoldxxdloxdc;,......,,,,,,,;:::;:::::;:cllooooodddddxxxxxddooodddxddddoool:;,,,,.....                                                                                                                                                                                                                                                                                        
                                                                    .:llllllllooolcldxxoloxxdlldl:;,......,..,,,;::::;;;;:,,:ccllodddddddxxxxddoooooooolc::clc;,............                                                                                                                                                                                                                                                                                      
                                                                   .;lllllllllloooolloxxolodxdlloc:;,........,,,,,,;,,,,,;;,,:cclooodddddxxxxdollc:;;;;,,,,,,,,........    .                                                                                                                                                                                                                                                                                      
                                                                 .,:cllllllllllooodolclxxdlldxdlccc:,.......,.,,..,,,,,.,,,,;:;:cloooddddddddoc;,,....................                                                                                                                                                                                                                                                                                            
                                                           .,...,,;;;;;;;;;;;;::cloddolldxxoloxdlcc:,....,.....,,,.,,....,,,,,,;;cccloddddddo:,......................                                                                                                                                                                                                                                                                                             
                                                         .,;;;;;,,,,,,,,,,,,,,,,,,,,;::;:lxxollddl:;,...........,,..,....,..,,,,,;;,:::ldddoc;............,,...........    .                                                                                                                                                                                                                                                                                      
                                                        .,;;;,,,,,,,,,,,,,,,,,,,,,,,,....,,codlcodl:,,.......................,..,;,,,,,coool:,....,,,,,,,,,,......,,,,...                                                                                                                                                                                                                                                                                         
                                                        .;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,;::lol;,..........................,,,,..,:clc;,...;cooolccccc::;;,,,,......                                                                                .,,,,.                                                                                                                                                 .,,,,,.                    .,,,,,.        .,,,,.  
                                                       .;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.......,;cl;..   ................  .........,;:;,...,:lodxxxxxddoollllcc:;;,.                                        ......                          .......  .kWNWWK;                                                     .okxxko.                         .....                ......                              .xWWWWX:                   .kWWWWX;       ,OWNNW0, 
                                                      .;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.........,::..         .........   ........,,,.....,:clodddddddooolollccc:;.                                       .xKKKKKk,                       :0KKKK0l. .kMMMMX;                                                     ,KMMMM0,                        cKKKKKl             .d0KKKK0;                             .xMMMMN:                   .OMMMMN:       ,0MMMMK, 
                                                  ..,,;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..........,;,.          . .....     ..........   ..;cloollllccc::;,,...,,.                                         ;KMMMMM0,                     :XMMMMWk.  .kMMMMX;                                                     ,KMMMM0,                        dMMMMMd            ,0WMMMMM0,                             .xMMMMN:                   .OMMMMN:       ,0MMMMK, 
                                                .,:c:;;;;;;;;;;;;;,,,,,,,,............................ .....           ..        ......       ..,;::cc::;;,,..   ....                                           ;KMMMMM0,                   :XMMMMWk.    :ooool.                                                     ,KMMMM0,                        dMMMMMd          .lXMMMMMWx.                              .xMMMMN:                   .OMMMMN:       .cooooc. 
                                             ..;:ccclccclllloooooddol::;;,,,,,.........................  ....                    ..  .          ....,,,,,...      . .                                            :XMMMMMO,                 ;KMMMMMO.     ;ooool.      .;looooooooooool.  .coooooooooooooooool:.      ,KMMMMNxooooooo,                dMMMMMd         .kWMMMMMXc.       ,cloooooooooooolc,      .xMMMMWOooooooooooolc,     .OMMMMN:       .:ooooc. 
                                          .,:cllccccccccccllccloxkko,...................................    ....                                  ...........       .                                             :XMMMMMO.               ;KMMMMMO,     .kMMMMX;    .oKWMMMMMMMMMMMMMWc  ;XMMMMMMMMMMMMMMMMMMMXo.    ,KMMMMMMMMMMMMMx.               dMMMMMd        :KMMMMMWO,       ,kNMMMMMMMMMMMMMMMMNk,    .xMMMMMMMMMMMMMMMMMMMNk,   .OMMMMN:       ,0MMMMK, 
                                       .,:lllcccllcccccccccc::cdxxo,.................................         ...                                   ..........                                                     :XMMMMWk.             ;KMMMMM0,      .kMMMMX;   .xWMMMMMMMMMMMMMMMWc  ;XMMMMMMMMMMMMMMMMMMMMWk.   ,KMMMMMMMMMMMMMx.               dMMMMMd      .dNMMMMMNd.       ;XMMMMMMMMMMMMMMMMMMMMX;   .xMMMMMMMMMMMMMMMMMMMMMX:  .OMMMMN:       ,0MMMMK, 
                                     ,:lolcc:cccccccclllcccc:coxxd:...................................          ....                                 .                                                              cXMMMMWk.           ,KMMMMM0,       .kMMMMX;   :XMMMMMWWWWWWWWWWWX:  ;KWWWWWWWWWWWWWWWWWMMMMN:   ,KMMMMMWWWWWWWWd                dMMMMMk,....;OWMMMMMK;        .xMMMMMWWWWWWWWWWWWMMMMMx.  .xMMMMMWWWWWWWWWWWWMMMMMk. .OMMMMN:       ,0MMMMK, 
                                  .,cllcc:::cccllccclcccccccclxkxl,.....................................         ....                                    .                                                           cNMMMMWx.         ,0MMMMM0,        .kMMMMX;   cNMMMMO;,,,,,,,,,,,.   .,,,,,,,,,,,,,,,;OMMMMWl   ,KMMMMKc,,,,,,,.                dMMMMMWNNNNNWMMMMMWx.         .kMMMMNo,,,,,,,,,,oNMMMMk.  .xMMMMWd,,,,,,,,,,oNMMMMO. .OMMMMN:       ,0MMMMK, 
                                .,:lcccc:::cccllccclcccccccccdkkd:...................................,,....        ....                                                                                               lNMMMMWx.       ,0MMMMMK,         .kMMMMX;   cNMMMMx.              .;:::::::::::::::l0MMMMWl   ,KMMMM0,                        dMMMMMMMMMMMMMMMMWo.          .kMMMMN:          :NMMMMk.  .xMMMMN:          ;XMMMMO. .OMMMMN:       ,0MMMMK, 
                              .;cccccc::::ccclllccllccccccccokkko,......................................,,....      ...                                                                                                lNMMMMWx.     ,OMMMMMK;          .kMMMMX;   cNMMMMx.              ;XMMMMMMMMMMMMMMMMMMMMMWl   ,KMMMM0,                        dMMMMMMMMMMMMMMMMWO,          .kMMMMN:          :NMMMMk.  .xMMMMN:          ;XMMMMO. .OMMMMN:       ,0MMMMK, 
                           .,:cclcccc::::ccclllllllcccccccclxkkkc................................................    .......                                                                                            oNMMMMWd.   ,OMMMMMK;           .kMMMMX;   cNMMMMx.              ;XMMMMMMMMMMMMMMMMMMMMMWl   ,KMMMM0,                        dMMMMMXxxxxx0WMMMMMXc.        .kMMMMN:          :NMMMMk.  .xMMMMN:          ;XMMMMO. .OMMMMN:       ,0MMMMK, 
                         .,:llcllccc::::ccclllllllcccccccccokkkd,..........................................................           ..                                                                                .oNMMMMWd,..OWMMMMK;            .kMMMMX;   cNMMMMx.              ;XMMMMNK0000000000NMMMMWl   ,KMMMM0,                        dMMMMMd     .lXMMMMMWx.       .kMMMMN:          :NMMMMk.  .xMMMMN:          ;XMMMMO. .OMMMMN:       ,0MMMMK, 
                       .,cclllcccc:::::ccllllllcccccccccc:lxkkkc......................................................,,;;;;,,...      ..                                                                                .dWMMMMNKkOWMMMMX:             .kMMMMX;   cNMMMMx.              ;XMMMMO, .       .xMMMMWl   ,KMMMM0,                        dMMMMMd       ,0WMMMMM0;      .kMMMMN:          :NMMMMk.  .xMMMMN:          ;XMMMMO. .OMMMMN:       ,0MMMMK, 
                     .,cccccccccc::;;:ccllllllccccccccccclxkkkd,.........................................................,,;:::::;,,.                                                                                     .dWMMMMMMMMMMMX:              .kMMMMX;   cNMMMMx.              ;XMMMM0:,,,,,,,,,;OMMMMWl   ,KMMMMKc,,,,,,,.                dMMMMMd        .xNMMMMMNo.    .kMMMMNo,,,,,,,,,,oNMMMMk.  .xMMMMN:          ;XMMMMO. .OMMMMNo,,,.   ,0MMMMK, 
                   .;cllccccccccc:;;:ccclllllccccccccccccdkkkkc.............................................................,,;:::ccc:,.                                                                                   .dWMMMMMMMMMXc               .kMMMMX;   cNMMMMx.              ,KMMMMMWNNNNNNNNNWWMMMMWl   ,0MMMMMWNNNNNNWd                dMMMMMd          cKMMMMMWO,   .xMMMMMWNNNNNNNNNNWMMMMMx.  .xMMMMN:          ;XMMMMO. .xMMMMMWNNWO.  ,0MMMMK, 
                 .;clllllccccccc:;;:cclllllllccccccccccclxkkkd,................................................................,,;:ccccc:,.                                                                                 .xWMMMMMMMXc                .kMMMMX;   cNMMMMx.              .dWMMMMMMMMMMMMMMMMMMMMWl    lNMMMMMMMMMMMMx.               dMMMMMd           ,kWMMMMMXc   ;XMMMMMMMMMMMMMMMMMMMMX;   .xMMMMN:          ;XMMMMO.  :XMMMMMMMM0,  ,0MMMMK, 
               .,cllllllllcccccc:;:ccllcllllccclccccccccdkkkkl,...................................................................,,;:cccc:,.                                                                                .xWMMMMMNl                 .kMMMMX;   cNMMMMx.               .lKWMMMMMMMMMMMMMMMMMMWc     :0WMMMMMMMMMMx.               dMMMMMd            .oNMMMMMN:   ,kNMMMMMMMMMMMMMMMMNk,    .xMMMMN:          ;XMMMMO.   ,kNMMMMMM0,  ,0MMMMK, 
              ,cllclcclcccccccc:;:ccllcclllcccccccccccclxkkkk:.......................................................................,,;:::::;,.                                                                              .cooooo;                   :ooool.   .loooo;                  .;coooooooooooooooool,      .,cooooooooo;                ,ooooo,              ,oooool.     ,cloooooooooooolc,       ;ooool.          .coooo:.     ,cloooo:.  .:ooooc. 
            .:llcllllllcclllllc:::cllcclllcccccccccccccokkkkd;..........................................................................,,;::cc:,.                                                                                                                                                                                                                                                                                                                
          .;llcllllllllcclllllc::clcccclllcccccccccccclxkkkOo,............................................................................,,;:ccc;.                                                                                                                                                                                                                                                                                                               
         ,lllcccllllllccccllllcccllccclllcllcccccccccclxkkkOl,...............................................................................,,:,.                                                                                                                                                                                                                                                                                                                
       .:olccccllcllllccccllllllllccclllccllccclllccccokOOOkc....................................................................................                                                                                                                                                                                                                                                                                                                 
      ,lolccccclcllllccccclllllllccccllcccccccclllccccokOOOx:...............................................................,,,,,,,................                                                                                                                                                                                                                                                                                                               
     ;olcclccccccllllcccccclllllcccclllccccccccccccccldkOkkx:.........................................................................................                                                                                                                                                                                                                                                                                                            
   .:olcllllccccllllllcccccllllcccclllcccccccccccccccldkkkkx;..........,,,..............................................................................                                                                                                                                                                                                                                                                                                          
  .cllllllccccclllllllccccclllccccclllccclllcccccccccldOkkOx;.........,,,,,...............................................................................                                                                                                                                                                                                                                                                                                        
 ,cllllllcccllllllclllccccclllccccllllllcllllcccclccclxOOOOx;........,,,,,,..................................................................................                                                                                                                                                                                                                                                                                                     
,clcllllcccllllllcccllccccllllccccllllllllllccccclccclxOOO0k:........,,,,,.....................................................................................                                                                                                                                                                                                                                                                                                   
:ccclllllllllllllcccllccccllllccclllccllllllcccccclcclx0000k:.......,,,,,,....................,,,................................................................                                                                                                                                                                                                                                                                                                 
cllllcllllllllcllcccllcccclolccccllcccllccllccclccccclx0000O:.......,,,,,,,.................,,,................,,,,,,,.............................................                                                                                                                                                                                                                                                                                               
llllllllcccllclllcccllcccclllcccllccccccccccccccccccclx000KOc.......,,,,,,.................,,,............,,,,,,,,,.................................................                                                                                                                                                                                                                                                                                              
lllllccccccllllllcccllcccclolcclllccclcclcccclccccccllx0K0K0c.......,,,,.................,,,,..........,,,,,,,,,......................................................                                                                                                                                                                                                                                                                                            
llllccccccllclllcc:cllllcllllclllcccllllllccccccccccclx0KKKKl........,..................,,,,..........,,,,,,,..........................................................                                                                                                                                                                                                                                                                                           
lllllccccclcclllc::cllllclollllllccllllllccllccccccclld0XKKKo,.......,,,,..............,,,...........,,,,,...................,.....................,,,,.................                                                                                                                                                                                                                                                                                          
lllcllcccllcllllc:::llllcloollllccclcclllllllcllcccccld0XXXXd,.......,,.,,...........,,,............,,,,,..........................................,,,,..................                                                                                                                                                                                                                                                                                         
lllcccclllllllllc:::cllllloolllcccccccllccclllllcclcccd0XXXXx,........,,,..........................,,,,,........................................,,,,,....................                                                                                                                                                                                                                                                                                         
lllccccllccllllllc:;:lllllolllccccccclllllccclcccclccco0XXXXO;.......,,,,.........................,,,,,.......................................,,,,,,......................                                                                                                                                                                                                                                                                                        
llccclcllccclloolllc::llloolllccccccclllccccccllccllcloOXXXNKc.........,.........................,,,,,...........,,..........................,,,,,.........................                                                                                                                                                                                                                                                                                       
cllcccccccccllllcccllccclooolcccccccllllccccccccccllccoOXXXNXo..................................,,,,,...........,,.........................,,,,,............................                                                                                                                                                                                                                                                                                      
olcccllllccllll:cc::clllloollccccccclllccllccccccccccclOXXXXNx,................................,,,,,.........,,,..........................,,,,,..............................                                                                                                                                                                                                                                                                                     
dlclllllllllllc::cc::ccllollccccccclllcclllcccclcccccclkXNNNNO;................,...............,,,,........,,,,.......................,,,,,,,,,..............................                                                                                                                                                                                                                                                                                     
dlcclloxxxdlllc;;ccc:ccllolcccccccclllcllcllccclcccccclxXNNNN0:........,,....,,,,.............,,,,,.......,,,........,,.............,,,,,,,,,,................................                                                                                                                                                                                                                                                                                    
'''